#!/usr/bin/env bash
# write a script that changes the IP of localhost to 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i '/localhost/ s/^127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
